### ISSUE TITLE
Components

### ISSUE THREAD

**Issue by lajanzen** [lajanzen/dogday#12]
#### Description

List of components that need to be built and what is needed for them.

#### Tasks

- [x] Component Link for LandingPage

- [x] Component Logo with Dog Picture and Title "DogDay" with background and shadow

- [x] Component LogoImg with Dog Picture and Title

- [x] Component Button with label and shadow

- [x] Component BackButton blue with arrow

- [x] Component NavBar
1. Logo
2. Three yellow dots with shadow with active effect blue that link to the pages

- [x] Component Dog Card with shadow
1. Profile picture 
2. dog name
3. dog age

- [x] Component Decision board
1. Yellow "Yes" and "No" button with shadow to decide whether I like the dog/sitter or not. 
2. blue background with shadow

- [x] Component LabledInput for Register and LogIn Form

- [x] Component ProfileCard
1. Info Component with Email, Handynummer, Stadt, Hundealter
2. Background circle in blue (sitter) or yellow (dog)
3. Picture
4. Name in the corresponding circle color

- [x] Component MatchCardDog
1. Card with dog image and info (name, age, contact details)

- [x] Component MatchCardSitter 
1. Card with dog image and info (name, experience, contact details)
