### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by lajanzen** [lajanzen/dogday#3]
#### Description

It's the landing page where the user can decide if he wants to register a dog or as a sitter or if he wants to log in. There is only a logo and the 3 links.

#### Screenshots

![image](https://user-images.githubusercontent.com/82370324/121493585-443e8900-c9d8-11eb-9e59-717668b13f00.png)

#### Tasks
- [x] Component Logo
- [x] Component Link blue - Register Dog with link to Register Dog Page
- [x] Component Link blue - Register Sitter with link to Register Sitter Page
- [x] Component Link yellow - Log in with link to log in page

- [x] Build Route
